#!/bin/bash

# taller 2 - Hadware y Sistemas Operativos
# -Ariel Fuenzalida
# -Henry Huerta
# -Diego Binimelis

# -INF2322-2

Listar_procesos(){
  echo
  read -p "ingresa tu nombre: " usuario

  > /tmp/procesos.txt
  contador = 1

}


main(){

  PS3 = "Seleccion una opcion: "

  opciones = ("Listar procesos" "Eliminar proceso" "listar detenidos" "activar servicio" "salir")

  select opc in  "${opciones[@]}"
  do
    case $opc in

      "listar procesos")
        listar_procesos
        ;;


      "Eliminar proceso")
        Eliminar_proceso
        ;;


      "listar detenidos")
        listar detenidos
        ;;


      "activar servicio"
        activar_servicio
        ;;


      "salir")
        echo "cierre del menu"
        break
        ;;
      *)
        echo "opcion incorrecta"
        ;;
    esac
  done
}
    
